// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4generated_quantities_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_dirichlet_multinomial_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_imputation_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_multi_beta_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_multi_beta_binomial_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_multi_beta_binomial_generate_date_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4glm_multi_beta_generate_data_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4generated_quantities_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4generated_quantities_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_dirichlet_multinomial_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_dirichlet_multinomial_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_imputation_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_imputation_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_multi_beta_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_multi_beta_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_multi_beta_binomial_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_multi_beta_binomial_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_multi_beta_binomial_generate_date_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_multi_beta_binomial_generate_date_mod, 0},
    {"_rcpp_module_boot_stan_fit4glm_multi_beta_generate_data_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4glm_multi_beta_generate_data_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_sccomp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
