// Generated by rstantools.  Do not edit by hand.

/*
    sccomp is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    sccomp is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with sccomp.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1
#include <stan/model/model_header.hpp>
namespace model_glm_multi_beta_binomial_generate_date_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 36, column 1 to column 18)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 37, column 1 to column 19)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 39, column 1 to column 47)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 47, column 2 to column 31)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 49, column 2 to column 22)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 51, column 2 to column 29)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 53, column 2 to column 47)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 54, column 2 to column 52)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 55, column 2 to column 51)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 56, column 2 to column 56)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 57, column 2 to column 17)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 58, column 2 to column 24)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 86, column 4 to column 27)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 87, column 4 to column 80)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 84, column 7 to line 88, column 3)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 62, column 4 to line 71, column 7)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 72, column 4 to line 82, column 46)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 60, column 27 to line 83, column 3)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 60, column 2 to line 88, column 3)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 91, column 13 to column 14)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 91, column 16 to column 17)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 91, column 6 to column 175)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 92, column 6 to column 36)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 90, column 39 to line 93, column 3)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 90, column 2 to line 93, column 3)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 95, column 15 to column 40)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 95, column 1 to column 40)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 98, column 5 to line 102, column 8)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 97, column 15 to line 103, column 2)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 97, column 1 to line 103, column 2)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 105, column 16 to column 67)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 105, column 2 to column 67)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 106, column 16 to column 103)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 106, column 2 to column 103)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 8, column 1 to column 7)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 9, column 1 to column 7)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 10, column 1 to column 7)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 11, column 1 to column 7)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 12, column 14 to column 15)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 12, column 1 to column 17)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 13, column 8 to column 9)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 13, column 11 to column 12)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 13, column 1 to column 16)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 14, column 9 to column 10)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 14, column 12 to column 13)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 14, column 2 to column 18)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 15, column 1 to column 18)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 16, column 1 to column 36)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 18, column 1 to column 20)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 19, column 1 to column 21)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 20, column 13 to column 27)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 20, column 1 to column 29)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 21, column 14 to column 29)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 21, column 1 to column 31)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 23, column 1 to column 37)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 24, column 30 to column 61)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 24, column 1 to column 63)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 25, column 1 to column 16)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 26, column 8 to column 9)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 26, column 11 to column 21)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 26, column 1 to column 42)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 28, column 2 to column 41)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 29, column 2 to column 35)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 33, column 9 to column 10)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 33, column 2 to column 56)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 36, column 8 to column 9)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 36, column 10 to column 11)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 37, column 8 to column 9)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 37, column 10 to column 11)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 39, column 8 to column 18)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 39, column 20 to column 23)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 47, column 25 to column 26)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 47, column 28 to column 29)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 49, column 9 to column 10)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 49, column 12 to column 13)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 51, column 26 to column 27)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 53, column 9 to column 10)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 53, column 12 to column 26)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 54, column 9 to column 23)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 54, column 24 to column 25)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 55, column 9 to column 10)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 55, column 12 to column 27)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 56, column 9 to column 24)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 56, column 25 to column 26)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 57, column 9 to column 10)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 57, column 11 to column 12)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 58, column 9 to column 10)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 58, column 11 to column 12)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 3, column 4 to line 4, column 56)",
                                                      " (in 'glm_multi_beta_binomial_generate_date', line 2, column 42 to line 5, column 3)"};
template <typename T0__>
Eigen::Matrix<stan::promote_args_t<stan::value_type_t<T0__>>, 1, -1>
average_by_col(const T0__& beta_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::value_type_t<T0__>>;
  const auto& beta = to_ref(beta_arg__);
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    current_statement__ = 89;
    return divide(multiply(rep_row_vector(1.0, rows(beta)), beta),
             rows(beta));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct average_by_col_functor__ {
template <typename T0__>
Eigen::Matrix<stan::promote_args_t<stan::value_type_t<T0__>>, 1, -1>
operator()(const T0__& beta, std::ostream* pstream__)  const 
{
return average_by_col(beta, pstream__);
}
};
#include <stan_meta_header.hpp>
class model_glm_multi_beta_binomial_generate_date final : public model_base_crtp<model_glm_multi_beta_binomial_generate_date> {
 private:
  int N;
  int M;
  int C;
  int A;
  std::vector<int> exposure;
  Eigen::Matrix<double, -1, -1> X;
  Eigen::Matrix<double, -1, -1> Xa;
  int is_truncated;
  double truncation_ajustment;
  int length_X_which;
  int length_XA_which;
  std::vector<int> X_which;
  std::vector<int> XA_which;
  int length_X_random_intercept_which;
  std::vector<int> X_random_intercept_which;
  int N_grouping;
  Eigen::Matrix<double, -1, -1> X_random_intercept;
  int create_intercept;
  int A_intercept_columns;
  Eigen::Matrix<double, -1, -1> X_intercept;
  int beta_random_intercept_2dim__;
 
 public:
  ~model_glm_multi_beta_binomial_generate_date() { }
  
  inline std::string model_name() const final { return "model_glm_multi_beta_binomial_generate_date"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1", "stancflags = "};
  }
  
  
  model_glm_multi_beta_binomial_generate_date(stan::io::var_context& context__,
                                              unsigned int random_seed__ = 0,
                                              std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_glm_multi_beta_binomial_generate_date_namespace::model_glm_multi_beta_binomial_generate_date";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 35;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 35;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 36;
      context__.validate_dims("data initialization","M","int",
          context__.to_vec());
      M = std::numeric_limits<int>::min();
      
      current_statement__ = 36;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 37;
      context__.validate_dims("data initialization","C","int",
          context__.to_vec());
      C = std::numeric_limits<int>::min();
      
      current_statement__ = 37;
      C = context__.vals_i("C")[(1 - 1)];
      current_statement__ = 38;
      context__.validate_dims("data initialization","A","int",
          context__.to_vec());
      A = std::numeric_limits<int>::min();
      
      current_statement__ = 38;
      A = context__.vals_i("A")[(1 - 1)];
      current_statement__ = 39;
      validate_non_negative_index("exposure", "N", N);
      current_statement__ = 40;
      context__.validate_dims("data initialization","exposure","int",
          context__.to_vec(N));
      exposure = std::vector<int>(N, std::numeric_limits<int>::min());
      
      current_statement__ = 40;
      assign(exposure, nil_index_list(), context__.vals_i("exposure"),
        "assigning variable exposure");
      current_statement__ = 41;
      validate_non_negative_index("X", "N", N);
      current_statement__ = 42;
      validate_non_negative_index("X", "C", C);
      current_statement__ = 43;
      context__.validate_dims("data initialization","X","double",
          context__.to_vec(N, C));
      X = Eigen::Matrix<double, -1, -1>(N, C);
      stan::math::fill(X, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 43;
        assign(X_flat__, nil_index_list(), context__.vals_r("X"),
          "assigning variable X_flat__");
        current_statement__ = 43;
        pos__ = 1;
        current_statement__ = 43;
        for (int sym1__ = 1; sym1__ <= C; ++sym1__) {
          current_statement__ = 43;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 43;
            assign(X,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              X_flat__[(pos__ - 1)], "assigning variable X");
            current_statement__ = 43;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 44;
      validate_non_negative_index("Xa", "N", N);
      current_statement__ = 45;
      validate_non_negative_index("Xa", "A", A);
      current_statement__ = 46;
      context__.validate_dims("data initialization","Xa","double",
          context__.to_vec(N, A));
      Xa = Eigen::Matrix<double, -1, -1>(N, A);
      stan::math::fill(Xa, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> Xa_flat__;
        current_statement__ = 46;
        assign(Xa_flat__, nil_index_list(), context__.vals_r("Xa"),
          "assigning variable Xa_flat__");
        current_statement__ = 46;
        pos__ = 1;
        current_statement__ = 46;
        for (int sym1__ = 1; sym1__ <= A; ++sym1__) {
          current_statement__ = 46;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 46;
            assign(Xa,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              Xa_flat__[(pos__ - 1)], "assigning variable Xa");
            current_statement__ = 46;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 47;
      context__.validate_dims("data initialization","is_truncated","int",
          context__.to_vec());
      is_truncated = std::numeric_limits<int>::min();
      
      current_statement__ = 47;
      is_truncated = context__.vals_i("is_truncated")[(1 - 1)];
      current_statement__ = 48;
      context__.validate_dims("data initialization","truncation_ajustment",
          "double",context__.to_vec());
      truncation_ajustment = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 48;
      truncation_ajustment = context__.vals_r("truncation_ajustment")[
          (1 - 1)];
      current_statement__ = 48;
      current_statement__ = 48;
      check_greater_or_equal(function__, "truncation_ajustment",
                             truncation_ajustment, 1);
      current_statement__ = 49;
      context__.validate_dims("data initialization","length_X_which","int",
          context__.to_vec());
      length_X_which = std::numeric_limits<int>::min();
      
      current_statement__ = 49;
      length_X_which = context__.vals_i("length_X_which")[(1 - 1)];
      current_statement__ = 50;
      context__.validate_dims("data initialization","length_XA_which","int",
          context__.to_vec());
      length_XA_which = std::numeric_limits<int>::min();
      
      current_statement__ = 50;
      length_XA_which = context__.vals_i("length_XA_which")[(1 - 1)];
      current_statement__ = 51;
      validate_non_negative_index("X_which", "length_X_which", length_X_which);
      current_statement__ = 52;
      context__.validate_dims("data initialization","X_which","int",
          context__.to_vec(length_X_which));
      X_which = std::vector<int>(length_X_which, std::numeric_limits<int>::min());
      
      current_statement__ = 52;
      assign(X_which, nil_index_list(), context__.vals_i("X_which"),
        "assigning variable X_which");
      current_statement__ = 53;
      validate_non_negative_index("XA_which", "length_XA_which",
                                  length_XA_which);
      current_statement__ = 54;
      context__.validate_dims("data initialization","XA_which","int",
          context__.to_vec(length_XA_which));
      XA_which = std::vector<int>(length_XA_which, std::numeric_limits<int>::min());
      
      current_statement__ = 54;
      assign(XA_which, nil_index_list(), context__.vals_i("XA_which"),
        "assigning variable XA_which");
      current_statement__ = 55;
      context__.validate_dims("data initialization",
          "length_X_random_intercept_which","int",context__.to_vec());
      length_X_random_intercept_which = std::numeric_limits<int>::min();
      
      current_statement__ = 55;
      length_X_random_intercept_which = context__.vals_i("length_X_random_intercept_which")[
          (1 - 1)];
      current_statement__ = 56;
      validate_non_negative_index("X_random_intercept_which",
                                  "length_X_random_intercept_which",
                                  length_X_random_intercept_which);
      current_statement__ = 57;
      context__.validate_dims("data initialization",
          "X_random_intercept_which","int",
          context__.to_vec(length_X_random_intercept_which));
      X_random_intercept_which = std::vector<int>(length_X_random_intercept_which, std::numeric_limits<int>::min());
      
      current_statement__ = 57;
      assign(X_random_intercept_which, nil_index_list(),
        context__.vals_i("X_random_intercept_which"),
        "assigning variable X_random_intercept_which");
      current_statement__ = 58;
      context__.validate_dims("data initialization","N_grouping","int",
          context__.to_vec());
      N_grouping = std::numeric_limits<int>::min();
      
      current_statement__ = 58;
      N_grouping = context__.vals_i("N_grouping")[(1 - 1)];
      current_statement__ = 59;
      validate_non_negative_index("X_random_intercept", "N", N);
      current_statement__ = 60;
      validate_non_negative_index("X_random_intercept", "N_grouping",
                                  N_grouping);
      current_statement__ = 61;
      context__.validate_dims("data initialization","X_random_intercept",
          "double",context__.to_vec(N, N_grouping));
      X_random_intercept = Eigen::Matrix<double, -1, -1>(N, N_grouping);
      stan::math::fill(X_random_intercept, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> X_random_intercept_flat__;
        current_statement__ = 61;
        assign(X_random_intercept_flat__, nil_index_list(),
          context__.vals_r("X_random_intercept"),
          "assigning variable X_random_intercept_flat__");
        current_statement__ = 61;
        pos__ = 1;
        current_statement__ = 61;
        for (int sym1__ = 1; sym1__ <= N_grouping; ++sym1__) {
          current_statement__ = 61;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 61;
            assign(X_random_intercept,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              X_random_intercept_flat__[(pos__ - 1)],
              "assigning variable X_random_intercept");
            current_statement__ = 61;
            pos__ = (pos__ + 1);}}
      }
      current_statement__ = 62;
      context__.validate_dims("data initialization","create_intercept","int",
          context__.to_vec());
      create_intercept = std::numeric_limits<int>::min();
      
      current_statement__ = 62;
      create_intercept = context__.vals_i("create_intercept")[(1 - 1)];
      current_statement__ = 62;
      current_statement__ = 62;
      check_greater_or_equal(function__, "create_intercept",
                             create_intercept, 0);
      current_statement__ = 62;
      current_statement__ = 62;
      check_less_or_equal(function__, "create_intercept", create_intercept, 1);
      current_statement__ = 63;
      context__.validate_dims("data initialization","A_intercept_columns",
          "int",context__.to_vec());
      A_intercept_columns = std::numeric_limits<int>::min();
      
      current_statement__ = 63;
      A_intercept_columns = context__.vals_i("A_intercept_columns")[(1 - 1)];
      current_statement__ = 63;
      current_statement__ = 63;
      check_greater_or_equal(function__, "A_intercept_columns",
                             A_intercept_columns, 0);
      current_statement__ = 64;
      validate_non_negative_index("X_intercept", "N", N);
      current_statement__ = 65;
      X_intercept = Eigen::Matrix<double, -1, -1>(N, 1);
      stan::math::fill(X_intercept, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 65;
      assign(X_intercept, nil_index_list(), to_matrix(rep_vector(1, N)),
        "assigning variable X_intercept");
      current_statement__ = 66;
      validate_non_negative_index("beta", "C", C);
      current_statement__ = 67;
      validate_non_negative_index("beta", "M", M);
      current_statement__ = 68;
      validate_non_negative_index("alpha", "A", A);
      current_statement__ = 69;
      validate_non_negative_index("alpha", "M", M);
      current_statement__ = 70;
      validate_non_negative_index("beta_random_intercept", "N_grouping",
                                  N_grouping);
      current_statement__ = 71;
      beta_random_intercept_2dim__ = std::numeric_limits<int>::min();
      
      current_statement__ = 71;
      beta_random_intercept_2dim__ = (M - 1);
      current_statement__ = 71;
      validate_non_negative_index("beta_random_intercept", "M - 1",
                                  beta_random_intercept_2dim__);
      current_statement__ = 72;
      validate_non_negative_index("counts_uncorrected", "N", N);
      current_statement__ = 73;
      validate_non_negative_index("counts_uncorrected", "M", M);
      current_statement__ = 74;
      validate_non_negative_index("counts", "N", N);
      current_statement__ = 75;
      validate_non_negative_index("counts", "M", M);
      current_statement__ = 76;
      validate_non_negative_index("generated_exposure", "N", N);
      current_statement__ = 77;
      validate_non_negative_index("my_X", "N", N);
      current_statement__ = 78;
      validate_non_negative_index("my_X", "length_X_which", length_X_which);
      current_statement__ = 79;
      validate_non_negative_index("my_beta", "length_X_which", length_X_which);
      current_statement__ = 80;
      validate_non_negative_index("my_beta", "M", M);
      current_statement__ = 81;
      validate_non_negative_index("my_Xa", "N", N);
      current_statement__ = 82;
      validate_non_negative_index("my_Xa", "length_XA_which", length_XA_which);
      current_statement__ = 83;
      validate_non_negative_index("my_alpha", "length_XA_which",
                                  length_XA_which);
      current_statement__ = 84;
      validate_non_negative_index("my_alpha", "M", M);
      current_statement__ = 85;
      validate_non_negative_index("mu", "M", M);
      current_statement__ = 86;
      validate_non_negative_index("mu", "N", N);
      current_statement__ = 87;
      validate_non_negative_index("precision", "M", M);
      current_statement__ = 88;
      validate_non_negative_index("precision", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += C * M;
      num_params_r__ += A * M;
      num_params_r__ += N_grouping * beta_random_intercept_2dim__;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_glm_multi_beta_binomial_generate_date_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<local_scalar_t__, -1, -1> beta;
      beta = Eigen::Matrix<local_scalar_t__, -1, -1>(C, M);
      stan::math::fill(beta, DUMMY_VAR__);
      
      current_statement__ = 1;
      beta = in__.matrix(C, M);
      Eigen::Matrix<local_scalar_t__, -1, -1> alpha;
      alpha = Eigen::Matrix<local_scalar_t__, -1, -1>(A, M);
      stan::math::fill(alpha, DUMMY_VAR__);
      
      current_statement__ = 2;
      alpha = in__.matrix(A, M);
      Eigen::Matrix<local_scalar_t__, -1, -1> beta_random_intercept;
      beta_random_intercept = Eigen::Matrix<local_scalar_t__, -1, -1>(N_grouping, beta_random_intercept_2dim__);
      stan::math::fill(beta_random_intercept, DUMMY_VAR__);
      
      current_statement__ = 3;
      beta_random_intercept = in__.matrix(N_grouping,
                                beta_random_intercept_2dim__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_glm_multi_beta_binomial_generate_date_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      Eigen::Matrix<double, -1, -1> beta;
      beta = Eigen::Matrix<double, -1, -1>(C, M);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      beta = in__.matrix(C, M);
      Eigen::Matrix<double, -1, -1> alpha;
      alpha = Eigen::Matrix<double, -1, -1>(A, M);
      stan::math::fill(alpha, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      alpha = in__.matrix(A, M);
      Eigen::Matrix<double, -1, -1> beta_random_intercept;
      beta_random_intercept = Eigen::Matrix<double, -1, -1>(N_grouping, beta_random_intercept_2dim__);
      stan::math::fill(beta_random_intercept, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 3;
      beta_random_intercept = in__.matrix(N_grouping,
                                beta_random_intercept_2dim__);
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= C; ++sym2__) {
          vars__.emplace_back(
            rvalue(beta,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "beta"));}}
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= A; ++sym2__) {
          vars__.emplace_back(
            rvalue(alpha,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "alpha"));}}
      for (int sym1__ = 1; sym1__ <= beta_random_intercept_2dim__; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N_grouping; ++sym2__) {
          vars__.emplace_back(
            rvalue(beta_random_intercept,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              "beta_random_intercept"));}}
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      std::vector<std::vector<int>> counts_uncorrected;
      counts_uncorrected = std::vector<std::vector<int>>(N, std::vector<int>(M, std::numeric_limits<int>::min()));
      
      Eigen::Matrix<double, -1, -1> counts;
      counts = Eigen::Matrix<double, -1, -1>(N, M);
      stan::math::fill(counts, std::numeric_limits<double>::quiet_NaN());
      
      std::vector<double> generated_exposure;
      generated_exposure = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, -1> my_X;
      my_X = Eigen::Matrix<double, -1, -1>(N, length_X_which);
      stan::math::fill(my_X, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 7;
      assign(my_X, nil_index_list(),
        rvalue(X,
          cons_list(index_omni(),
            cons_list(index_multi(X_which), nil_index_list())), "X"),
        "assigning variable my_X");
      Eigen::Matrix<double, -1, -1> my_beta;
      my_beta = Eigen::Matrix<double, -1, -1>(length_X_which, M);
      stan::math::fill(my_beta, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 8;
      assign(my_beta, nil_index_list(),
        rvalue(beta,
          cons_list(index_multi(X_which),
            cons_list(index_omni(), nil_index_list())), "beta"),
        "assigning variable my_beta");
      Eigen::Matrix<double, -1, -1> my_Xa;
      my_Xa = Eigen::Matrix<double, -1, -1>(N, length_XA_which);
      stan::math::fill(my_Xa, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 9;
      assign(my_Xa, nil_index_list(),
        rvalue(Xa,
          cons_list(index_omni(),
            cons_list(index_multi(XA_which), nil_index_list())), "Xa"),
        "assigning variable my_Xa");
      Eigen::Matrix<double, -1, -1> my_alpha;
      my_alpha = Eigen::Matrix<double, -1, -1>(length_XA_which, M);
      stan::math::fill(my_alpha, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 10;
      assign(my_alpha, nil_index_list(),
        rvalue(alpha,
          cons_list(index_multi(XA_which),
            cons_list(index_omni(), nil_index_list())), "alpha"),
        "assigning variable my_alpha");
      Eigen::Matrix<double, -1, -1> mu;
      mu = Eigen::Matrix<double, -1, -1>(M, N);
      stan::math::fill(mu, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, -1> precision;
      precision = Eigen::Matrix<double, -1, -1>(M, N);
      stan::math::fill(precision, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 19;
      if (logical_eq(create_intercept, 1)) {
        current_statement__ = 16;
        assign(mu, nil_index_list(),
          transpose(
            multiply(append_col(to_matrix(rep_vector(1, N)), my_X),
              append_row(
                average_by_col(
                  rvalue(beta,
                    cons_list(index_min_max(1, A_intercept_columns),
                      cons_list(index_omni(), nil_index_list())), "beta"), pstream__),
                my_beta))), "assigning variable mu");
        current_statement__ = 17;
        assign(precision, nil_index_list(),
          divide(
            transpose(
              multiply(append_col(to_matrix(rep_vector(1, N)), my_Xa),
                append_row(
                  average_by_col(
                    rvalue(alpha,
                      cons_list(index_min_max(1, A_intercept_columns),
                        cons_list(index_omni(), nil_index_list())), "alpha"), pstream__),
                  my_alpha))),
            (is_truncated ?
               stan::math::promote_scalar<double>(truncation_ajustment) :
               stan::math::promote_scalar<double>(1))),
          "assigning variable precision");
      } else {
        current_statement__ = 13;
        assign(mu, nil_index_list(), transpose(multiply(my_X, my_beta)),
          "assigning variable mu");
        current_statement__ = 14;
        assign(precision, nil_index_list(),
          divide(transpose(multiply(my_Xa, my_alpha)),
            (is_truncated ?
               stan::math::promote_scalar<double>(truncation_ajustment) :
               stan::math::promote_scalar<double>(1))),
          "assigning variable precision");
      }
      current_statement__ = 25;
      if (logical_gt(length_X_random_intercept_which, 0)) {
        current_statement__ = 20;
        validate_non_negative_index("mu_random_intercept", "M", M);
        current_statement__ = 21;
        validate_non_negative_index("mu_random_intercept", "N", N);
        Eigen::Matrix<double, -1, -1> mu_random_intercept;
        mu_random_intercept = Eigen::Matrix<double, -1, -1>(M, N);
        stan::math::fill(mu_random_intercept, std::numeric_limits<double>::quiet_NaN());
        
        current_statement__ = 22;
        assign(mu_random_intercept, nil_index_list(),
          append_row(
            transpose(
              multiply(
                rvalue(X_random_intercept,
                  cons_list(index_omni(),
                    cons_list(index_multi(X_random_intercept_which),
                      nil_index_list())), "X_random_intercept"),
                rvalue(beta_random_intercept,
                  cons_list(index_multi(X_random_intercept_which),
                    cons_list(index_omni(), nil_index_list())),
                  "beta_random_intercept"))), rep_row_vector(0, N)),
          "assigning variable mu_random_intercept");
        current_statement__ = 23;
        assign(mu, nil_index_list(),
          add(stan::model::deep_copy(mu), mu_random_intercept),
          "assigning variable mu");
      } 
      current_statement__ = 27;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 26;
        assign(mu,
          cons_list(index_omni(), cons_list(index_uni(i), nil_index_list())),
          softmax(
            stan::model::deep_copy(
              rvalue(mu,
                cons_list(index_omni(),
                  cons_list(index_uni(i), nil_index_list())), "mu"))),
          "assigning variable mu");}
      current_statement__ = 30;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 28;
        assign(counts_uncorrected,
          cons_list(index_uni(i), cons_list(index_omni(), nil_index_list())),
          beta_binomial_rng(exposure[(i - 1)],
            elt_multiply(
              rvalue(mu,
                cons_list(index_omni(),
                  cons_list(index_uni(i), nil_index_list())), "mu"),
              stan::math::exp(
                rvalue(precision,
                  cons_list(index_omni(),
                    cons_list(index_uni(i), nil_index_list())), "precision"))),
            elt_multiply(
              subtract(1.0,
                rvalue(mu,
                  cons_list(index_omni(),
                    cons_list(index_uni(i), nil_index_list())), "mu")),
              stan::math::exp(
                rvalue(precision,
                  cons_list(index_omni(),
                    cons_list(index_uni(i), nil_index_list())), "precision"))),
            base_rng__), "assigning variable counts_uncorrected");}
      current_statement__ = 32;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 31;
        assign(generated_exposure, cons_list(index_uni(n), nil_index_list()),
          sum(counts_uncorrected[(n - 1)]),
          "assigning variable generated_exposure");}
      current_statement__ = 34;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 33;
        assign(counts, cons_list(index_uni(n), nil_index_list()),
          multiply(
            divide(to_row_vector(counts_uncorrected[(n - 1)]),
              generated_exposure[(n - 1)]), exposure[(n - 1)]),
          "assigning variable counts");}
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          vars__.emplace_back(
            counts_uncorrected[(sym2__ - 1)][(sym1__ - 1)]);}}
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          vars__.emplace_back(
            rvalue(counts,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "counts"));}
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        vars__.emplace_back(generated_exposure[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= length_X_which; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          vars__.emplace_back(
            rvalue(my_X,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "my_X"));}}
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= length_X_which; ++sym2__) {
          vars__.emplace_back(
            rvalue(my_beta,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "my_beta"));
        }}
      for (int sym1__ = 1; sym1__ <= length_XA_which; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          vars__.emplace_back(
            rvalue(my_Xa,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "my_Xa"));}}
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= length_XA_which; ++sym2__) {
          vars__.emplace_back(
            rvalue(my_alpha,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "my_alpha"));
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
          vars__.emplace_back(
            rvalue(mu,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "mu"));}}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
          vars__.emplace_back(
            rvalue(precision,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "precision"));
        }}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      Eigen::Matrix<double, -1, -1> beta;
      beta = Eigen::Matrix<double, -1, -1>(C, M);
      stan::math::fill(beta, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> beta_flat__;
        current_statement__ = 1;
        assign(beta_flat__, nil_index_list(), context__.vals_r("beta"),
          "assigning variable beta_flat__");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 1;
          for (int sym2__ = 1; sym2__ <= C; ++sym2__) {
            current_statement__ = 1;
            assign(beta,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              beta_flat__[(pos__ - 1)], "assigning variable beta");
            current_statement__ = 1;
            pos__ = (pos__ + 1);}}
      }
      Eigen::Matrix<double, -1, -1> alpha;
      alpha = Eigen::Matrix<double, -1, -1>(A, M);
      stan::math::fill(alpha, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> alpha_flat__;
        current_statement__ = 2;
        assign(alpha_flat__, nil_index_list(), context__.vals_r("alpha"),
          "assigning variable alpha_flat__");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
          current_statement__ = 2;
          for (int sym2__ = 1; sym2__ <= A; ++sym2__) {
            current_statement__ = 2;
            assign(alpha,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              alpha_flat__[(pos__ - 1)], "assigning variable alpha");
            current_statement__ = 2;
            pos__ = (pos__ + 1);}}
      }
      Eigen::Matrix<double, -1, -1> beta_random_intercept;
      beta_random_intercept = Eigen::Matrix<double, -1, -1>(N_grouping, beta_random_intercept_2dim__);
      stan::math::fill(beta_random_intercept, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> beta_random_intercept_flat__;
        current_statement__ = 3;
        assign(beta_random_intercept_flat__, nil_index_list(),
          context__.vals_r("beta_random_intercept"),
          "assigning variable beta_random_intercept_flat__");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= beta_random_intercept_2dim__; ++sym1__) {
          current_statement__ = 3;
          for (int sym2__ = 1; sym2__ <= N_grouping; ++sym2__) {
            current_statement__ = 3;
            assign(beta_random_intercept,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              beta_random_intercept_flat__[(pos__ - 1)],
              "assigning variable beta_random_intercept");
            current_statement__ = 3;
            pos__ = (pos__ + 1);}}
      }
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= C; ++sym2__) {
          vars__.emplace_back(
            rvalue(beta,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "beta"));}}
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= A; ++sym2__) {
          vars__.emplace_back(
            rvalue(alpha,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())), "alpha"));}}
      for (int sym1__ = 1; sym1__ <= beta_random_intercept_2dim__; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N_grouping; ++sym2__) {
          vars__.emplace_back(
            rvalue(beta_random_intercept,
              cons_list(index_uni(sym2__),
                cons_list(index_uni(sym1__), nil_index_list())),
              "beta_random_intercept"));}}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("beta");
    names__.emplace_back("alpha");
    names__.emplace_back("beta_random_intercept");
    names__.emplace_back("counts_uncorrected");
    names__.emplace_back("counts");
    names__.emplace_back("generated_exposure");
    names__.emplace_back("my_X");
    names__.emplace_back("my_beta");
    names__.emplace_back("my_Xa");
    names__.emplace_back("my_alpha");
    names__.emplace_back("mu");
    names__.emplace_back("precision");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(C),
                                             static_cast<size_t>(M)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(A),
                                             static_cast<size_t>(M)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N_grouping),
                                             static_cast<size_t>(beta_random_intercept_2dim__)
                                             });
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N),
                                             static_cast<size_t>(M)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N),
                                             static_cast<size_t>(M)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N),
                                             static_cast<size_t>(length_X_which)
                                             });
    
    dimss__.emplace_back(std::vector<size_t>{
                                             static_cast<size_t>(length_X_which)
                                             , static_cast<size_t>(M)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(N),
                                             static_cast<size_t>(length_XA_which)
                                             });
    
    dimss__.emplace_back(std::vector<size_t>{
                                             static_cast<size_t>(length_XA_which)
                                             , static_cast<size_t>(M)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(M),
                                             static_cast<size_t>(N)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(M),
                                             static_cast<size_t>(N)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= C; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          }}
      }}
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= A; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "alpha" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          }}
      }}
    for (int sym1__ = 1; sym1__ <= beta_random_intercept_2dim__; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= N_grouping; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "beta_random_intercept" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          }}
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "counts_uncorrected" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "counts" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "generated_exposure" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= length_X_which; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "my_X" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= length_X_which; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "my_beta" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= length_XA_which; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "my_Xa" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= length_XA_which; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "my_alpha" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "precision" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= C; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "beta" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          }}
      }}
    for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= A; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "alpha" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          }}
      }}
    for (int sym1__ = 1; sym1__ <= beta_random_intercept_2dim__; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= N_grouping; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "beta_random_intercept" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          }}
      }}
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "counts_uncorrected" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "counts" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "generated_exposure" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= length_X_which; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "my_X" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= length_X_which; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "my_beta" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= length_XA_which; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "my_Xa" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= M; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= length_XA_which; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "my_alpha" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= M; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "precision" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            }}
        }}
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"beta\",\"type\":{\"name\":\"matrix\",\"rows\":" << C << ",\"cols\":" << M << "},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"matrix\",\"rows\":" << A << ",\"cols\":" << M << "},\"block\":\"parameters\"},{\"name\":\"beta_random_intercept\",\"type\":{\"name\":\"matrix\",\"rows\":" << N_grouping << ",\"cols\":" << beta_random_intercept_2dim__ << "},\"block\":\"parameters\"},{\"name\":\"counts_uncorrected\",\"type\":{\"name\":\"array\",\"length\":" << N << ",\"element_type\":{\"name\":\"array\",\"length\":" << M << ",\"element_type\":{\"name\":\"int\"}}},\"block\":\"generated_quantities\"},{\"name\":\"counts\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << M << "},\"block\":\"generated_quantities\"},{\"name\":\"generated_exposure\",\"type\":{\"name\":\"array\",\"length\":" << N << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"my_X\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << length_X_which << "},\"block\":\"generated_quantities\"},{\"name\":\"my_beta\",\"type\":{\"name\":\"matrix\",\"rows\":" << length_X_which << ",\"cols\":" << M << "},\"block\":\"generated_quantities\"},{\"name\":\"my_Xa\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << length_XA_which << "},\"block\":\"generated_quantities\"},{\"name\":\"my_alpha\",\"type\":{\"name\":\"matrix\",\"rows\":" << length_XA_which << ",\"cols\":" << M << "},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"matrix\",\"rows\":" << M << ",\"cols\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"precision\",\"type\":{\"name\":\"matrix\",\"rows\":" << M << ",\"cols\":" << N << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"beta\",\"type\":{\"name\":\"matrix\",\"rows\":" << C << ",\"cols\":" << M << "},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"matrix\",\"rows\":" << A << ",\"cols\":" << M << "},\"block\":\"parameters\"},{\"name\":\"beta_random_intercept\",\"type\":{\"name\":\"matrix\",\"rows\":" << N_grouping << ",\"cols\":" << beta_random_intercept_2dim__ << "},\"block\":\"parameters\"},{\"name\":\"counts_uncorrected\",\"type\":{\"name\":\"array\",\"length\":" << N << ",\"element_type\":{\"name\":\"array\",\"length\":" << M << ",\"element_type\":{\"name\":\"int\"}}},\"block\":\"generated_quantities\"},{\"name\":\"counts\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << M << "},\"block\":\"generated_quantities\"},{\"name\":\"generated_exposure\",\"type\":{\"name\":\"array\",\"length\":" << N << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"my_X\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << length_X_which << "},\"block\":\"generated_quantities\"},{\"name\":\"my_beta\",\"type\":{\"name\":\"matrix\",\"rows\":" << length_X_which << ",\"cols\":" << M << "},\"block\":\"generated_quantities\"},{\"name\":\"my_Xa\",\"type\":{\"name\":\"matrix\",\"rows\":" << N << ",\"cols\":" << length_XA_which << "},\"block\":\"generated_quantities\"},{\"name\":\"my_alpha\",\"type\":{\"name\":\"matrix\",\"rows\":" << length_XA_which << ",\"cols\":" << M << "},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"matrix\",\"rows\":" << M << ",\"cols\":" << N << "},\"block\":\"generated_quantities\"},{\"name\":\"precision\",\"type\":{\"name\":\"matrix\",\"rows\":" << M << ",\"cols\":" << N << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_glm_multi_beta_binomial_generate_date_namespace::model_glm_multi_beta_binomial_generate_date;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_glm_multi_beta_binomial_generate_date_namespace::profiles__;
}
#endif
#endif
