# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("generated_quantities", "glm_dirichlet_multinomial", "glm_imputation", "glm_multi_beta", "glm_multi_beta_binomial", "glm_multi_beta_binomial_generate_date", "glm_multi_beta_generate_data")

# load each stan module
Rcpp::loadModule("stan_fit4generated_quantities_mod", what = TRUE)
Rcpp::loadModule("stan_fit4glm_dirichlet_multinomial_mod", what = TRUE)
Rcpp::loadModule("stan_fit4glm_imputation_mod", what = TRUE)
Rcpp::loadModule("stan_fit4glm_multi_beta_mod", what = TRUE)
Rcpp::loadModule("stan_fit4glm_multi_beta_binomial_mod", what = TRUE)
Rcpp::loadModule("stan_fit4glm_multi_beta_binomial_generate_date_mod", what = TRUE)
Rcpp::loadModule("stan_fit4glm_multi_beta_generate_data_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
